language: csharp
solution: DataProcessSolution.sln
install:
  - nuget restore DataProcessSolution.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release DataProcessSolution.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./DataProcessSolution.Tests/bin/Release/DataProcessSolution.Tests.dll
