//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProcessSolution.API.Backend.FileHandlerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileHandlerService.IFileHandlerService")]
    public interface IFileHandlerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileHandlerService/ProcessFile", ReplyAction="http://tempuri.org/IFileHandlerService/ProcessFileResponse")]
        string ProcessFile(DataProcessSolution.FileHandlingClient.FileHandlerServiceReference.ProcessedFile processedFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileHandlerService/ProcessFile", ReplyAction="http://tempuri.org/IFileHandlerService/ProcessFileResponse")]
        System.Threading.Tasks.Task<string> ProcessFileAsync(DataProcessSolution.FileHandlingClient.FileHandlerServiceReference.ProcessedFile processedFile);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileHandlerServiceChannel : DataProcessSolution.API.Backend.FileHandlerService.IFileHandlerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileHandlerServiceClient : System.ServiceModel.ClientBase<DataProcessSolution.API.Backend.FileHandlerService.IFileHandlerService>, DataProcessSolution.API.Backend.FileHandlerService.IFileHandlerService {
        
        public FileHandlerServiceClient() {
        }
        
        public FileHandlerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileHandlerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileHandlerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileHandlerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ProcessFile(DataProcessSolution.FileHandlingClient.FileHandlerServiceReference.ProcessedFile processedFile) {
            return base.Channel.ProcessFile(processedFile);
        }
        
        public System.Threading.Tasks.Task<string> ProcessFileAsync(DataProcessSolution.API.Backend.Utilities.ProcessedFile processedFile) {
            return base.Channel.ProcessFileAsync(processedFile);
        }
    }
}
